FROM golang:1.26.3-alpine@sha256:f44b851aa23dfa219d18db6eab743203245429d355cb619cf96a2ffe2a84ba7a AS build
ARG HUGO_VERSION=0.162.1
ARG HUGO_SHA256=4bfcdb092d0306586f1b72e5687787ead053faab2d71f09951d3c5fecde66873
RUN apk add --no-cache git wget tar \
  && wget -qO /tmp/hugo.tar.gz "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.tar.gz" \
  && echo "${HUGO_SHA256}  /tmp/hugo.tar.gz" | sha256sum -c - \
  && tar -xzf /tmp/hugo.tar.gz -C /usr/local/bin \
  && rm /tmp/hugo.tar.gz \
  && hugo version
WORKDIR /src
COPY . .
ARG BASE_URL=
RUN if [ -n "$BASE_URL" ]; then \
      hugo --minify --baseURL "$BASE_URL"; \
    else \
      hugo --minify; \
    fi

FROM nginxinc/nginx-unprivileged:stable-alpine-slim@sha256:bcb4860e2d7877cf140e4c945f5f9cb304ccb5efbe1dd4fa606a2206142241bf
# Patch Alpine-packages onafhankelijk van de (soms achterlopende) base-image
# rebuild; houdt de Trivy-scan groen bij CVE's die Alpine al gefixt heeft.
USER root
RUN apk upgrade --no-cache
USER 101
COPY --from=build /src/public/ /usr/share/nginx/html/
COPY container/nginx.conf /etc/nginx/nginx.conf
EXPOSE 8080
