name: Valideer publiccode.yml

on:
  pull_request:
    paths:
      - publiccode.yml
      - .github/workflows/publiccode-validate.yaml
  push:
    branches: [main]
    paths:
      - publiccode.yml

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Installeer publiccode-parser
        run: go install github.com/italia/publiccode-parser-go/v5/publiccode-parser@latest

      - name: Valideer publiccode.yml
        run: publiccode-parser publiccode.yml
